"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log("Hello Word! ");
var readlinesync = require("readline-sync");
var quantidade;
var altura;
var tipo;
var resposta;
var palavra;
quantidade = readlinesync.questionInt("\nDigite um valor do tipo Inteiro: ", { limitMessage: "Digite um numero inteiro" });
console.log("O valor inteiro digitado foi: " + quantidade);
altura = readlinesync.questionFloat("\nDigite um valor do tipo decimal: ", { limitMessage: "Digite um numero decimal" });
console.log("O valor decimal digitado foi: " + altura);
console.log("\nDigite um valor do tipo Char - um único caractere: ");
tipo = readlinesync.keyIn();
console.log("\nO valor char digitado foi: " + tipo);
resposta = readlinesync.keyInYNStrict("\nDigite um valor do tipo Boolean: ");
console.log("O valor boolean digitado foi: " + resposta);
palavra = readlinesync.question("\nDigite um valor do tipo string: ");
console.log("O valor string digitado foi: " + palavra);
